[package]
name = "rlibc"
version = "0.13.0"
authors = ["Ben Harris <mail@bharr.is>"]

[lib]
name = "rlibc"
path = "src/lib.rs"

[dependencies.core]
git = "https://github.com/sondrele/rust-libcore.git"
